services:
  api-gateway:
    image: api-ivr-mdw/api-gateway:latest
    build:
      context: ..
      dockerfile: ./Dockerfile
      args: { APP_NAME: api-gateway }
    env_file:
      - ./.env
    environment:
      APP_ENV: prod          # asegura modo prod (tu app tomar√° process.env)
    ports:
      - "8080:3000"
    depends_on:
      - mulesoft-customer-ms
      - redis

  mulesoft-customer-ms:
    image: api-ivr-mdw/mulesoft-customer-ms:latest
    build:
      context: ..
      dockerfile: ./Dockerfile
      args: { APP_NAME: mulesoft-customer-ms }
    env_file:
      - ./.env
    environment:
      APP_ENV: prod
    depends_on:
      - redis

  mulesoft-digital-billing-ms:
    image: api-ivr-mdw/mulesoft-digital-billing-ms:latest
    build:
      context: ..
      dockerfile: ./Dockerfile
      args: { APP_NAME: mulesoft-digital-billing-ms }
    env_file:
      - ./.env
    environment:
      APP_ENV: prod
    depends_on:
      - redis
      
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
